version: "3.9"
services:
  user-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - PORT=3000
    ports:
      - "3001:3000"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
