apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: app
          image: ghcr.io/your/repo/user-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
