name: Bootcamp CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Python test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run Python tests (if present)
        run: |
          if [ -d capstone/services/user-service ]; then
            echo "No tests yet — add them!"
          else
            echo "Scaffold CI running"
          fi
      - name: Markdown Lint
        uses: avto-dev/markdown-lint@v1
        with:
          args: "**/*.md"

  docker-build-and-scan:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/user-service:latest -f docker/Dockerfile .
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}/user-service:latest
          format: table
          exit-code: 0
      - name: Push image
        run: docker push ghcr.io/${{ github.repository }}/user-service:latest
